name: Android CI

on:
  push:
    branches: [ deploy-internal ]
  pull_request:
    branches: [ deploy-internal ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew app:bundleRelease

      # Sign Android App (.aab)
      - name: Sign Android .aab
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -la

      # Upload app
      - name: Upload to Google Play Store/Console
      - uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.fjbg.weather
          releaseFiles: "build/release"
          track: internal
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          # mappingFile: app/build/outputs/mapping/release/mapping.txt

