name: Android CI

on:
  push:
    branches: [ deploy-internal ]
  pull_request:
    branches: [ deploy-internal ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - uses: Tlaster/android-sign@v1
      - name: Sign app APK
        with:
          releaseDirectory: |
            app/build/outputs/apk/release
            app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: "Azhagth0tt#12345k"
          keyPassword: "Azhagth0tt#12345k"
        - env:
          BUILD_TOOLS_VERSION: "30.0.2"